# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_city', models.CharField(max_length=200)),
                ('neighborhood1', models.CharField(max_length=200)),
                ('end_city', models.CharField(max_length=200)),
                ('neighborhood2', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
